version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: magic-cards-app
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      JWT_SECRET: your_jwt_secret_key
      JWT_EXPIRES_IN: 1h
      MONGO_URI: mongodb://admin:admin@10.0.2.71:27017/deckTrade?authSource=admin
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - app-network

  web:
    build:
      context: ./g3-frontend-next
      dockerfile: Dockerfile
    container_name: magic-cards-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001/api}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
