version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: magic-cards-app
    ports:
      - "3001:3001"
    environment:
      - AWS_S3_BUCKET=your_s3_bucket_name
      - AWS_S3_REGION=your_s3_region
      - AWS_S3_ACCESS_KEY_ID=your_s3_access_key_id
      - AWS_S3_SECRET_ACCESS_KEY=your_s3_secret_access_key
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=1h
      - MONGO_URI=mongodb://mongo:27017/deckTrade
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - app-network

  mongo:
    image: mongo:6
    container_name: mongo
    profiles:
      - dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  web:
    build:
      context: ./g3-frontend-next
      dockerfile: Dockerfile
    container_name: magic-cards-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001/api}
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
